#import "TimezoneData.h"

@implementation TZCity
+ (instancetype)cityWithTZ:(NSString *)tz en:(NSString *)en cn:(NSString *)cn {
    TZCity *c = [[TZCity alloc] init];
    c.tz = tz; c.en = en; c.cn = cn;
    return c;
}
@end

@implementation TZRegion
+ (instancetype)regionWithEN:(NSString *)en cn:(NSString *)cn cities:(NSArray<TZCity *> *)cities {
    TZRegion *r = [[TZRegion alloc] init];
    r.en = en; r.cn = cn; r.cities = cities;
    return r;
}
@end

#define C(a,b,c) [TZCity cityWithTZ:@a en:@b cn:@c]

static NSArray<TZRegion *> *sRegions = nil;
static NSDictionary<NSString *, TZCity *> *sIndex = nil;

@implementation TimezoneData

+ (void)initialize {
    if (self != [TimezoneData class]) return;

    sRegions = @[
        [TZRegion regionWithEN:@"Africa" cn:@"非洲" cities:@[
            C("Africa/Abidjan","Abidjan","阿比让"),
            C("Africa/Accra","Accra","阿克拉"),
            C("Africa/Addis_Ababa","Addis Ababa","亚的斯亚贝巴"),
            C("Africa/Algiers","Algiers","阿尔及尔"),
            C("Africa/Asmara","Asmara","阿斯马拉"),
            C("Africa/Bamako","Bamako","巴马科"),
            C("Africa/Bangui","Bangui","班吉"),
            C("Africa/Banjul","Banjul","班珠尔"),
            C("Africa/Bissau","Bissau","比绍"),
            C("Africa/Blantyre","Blantyre","布兰太尔"),
            C("Africa/Brazzaville","Brazzaville","布拉柴维尔"),
            C("Africa/Bujumbura","Bujumbura","布琼布拉"),
            C("Africa/Cairo","Cairo","开罗"),
            C("Africa/Casablanca","Casablanca","卡萨布兰卡"),
            C("Africa/Ceuta","Ceuta","休达"),
            C("Africa/Conakry","Conakry","科纳克里"),
            C("Africa/Dakar","Dakar","达喀尔"),
            C("Africa/Dar_es_Salaam","Dar es Salaam","达累斯萨拉姆"),
            C("Africa/Djibouti","Djibouti","吉布提"),
            C("Africa/Douala","Douala","杜阿拉"),
            C("Africa/El_Aaiun","El Aaiun","阿尤恩"),
            C("Africa/Freetown","Freetown","弗里敦"),
            C("Africa/Gaborone","Gaborone","哈博罗内"),
            C("Africa/Harare","Harare","哈拉雷"),
            C("Africa/Johannesburg","Johannesburg","约翰内斯堡"),
            C("Africa/Juba","Juba","朱巴"),
            C("Africa/Kampala","Kampala","坎帕拉"),
            C("Africa/Khartoum","Khartoum","喀土穆"),
            C("Africa/Kigali","Kigali","基加利"),
            C("Africa/Kinshasa","Kinshasa","金沙萨"),
            C("Africa/Lagos","Lagos","拉各斯"),
            C("Africa/Libreville","Libreville","利伯维尔"),
            C("Africa/Lome","Lome","洛美"),
            C("Africa/Luanda","Luanda","罗安达"),
            C("Africa/Lubumbashi","Lubumbashi","卢本巴希"),
            C("Africa/Lusaka","Lusaka","卢萨卡"),
            C("Africa/Malabo","Malabo","马拉博"),
            C("Africa/Maputo","Maputo","马普托"),
            C("Africa/Maseru","Maseru","马塞卢"),
            C("Africa/Mbabane","Mbabane","姆巴巴内"),
            C("Africa/Mogadishu","Mogadishu","摩加迪沙"),
            C("Africa/Monrovia","Monrovia","蒙罗维亚"),
            C("Africa/Nairobi","Nairobi","内罗毕"),
            C("Africa/Ndjamena","Ndjamena","恩贾梅纳"),
            C("Africa/Niamey","Niamey","尼亚美"),
            C("Africa/Nouakchott","Nouakchott","努瓦克肖特"),
            C("Africa/Ouagadougou","Ouagadougou","瓦加杜古"),
            C("Africa/Porto-Novo","Porto-Novo","波多诺伏"),
            C("Africa/Sao_Tome","Sao Tome","圣多美"),
            C("Africa/Tripoli","Tripoli","的黎波里"),
            C("Africa/Tunis","Tunis","突尼斯"),
            C("Africa/Windhoek","Windhoek","温得和克"),
        ]],
        [TZRegion regionWithEN:@"America" cn:@"美洲" cities:@[
            C("America/Adak","Adak","阿达克"),
            C("America/Anchorage","Anchorage","安克雷奇"),
            C("America/Anguilla","Anguilla","安圭拉"),
            C("America/Antigua","Antigua","安提瓜"),
            C("America/Araguaina","Araguaina","阿拉瓜伊纳"),
            C("America/Argentina/Buenos_Aires","Buenos Aires","布宜诺斯艾利斯"),
            C("America/Argentina/Cordoba","Cordoba (AR)","科尔多瓦"),
            C("America/Argentina/Mendoza","Mendoza","门多萨"),
            C("America/Argentina/Ushuaia","Ushuaia","乌斯怀亚"),
            C("America/Aruba","Aruba","阿鲁巴"),
            C("America/Asuncion","Asuncion","亚松森"),
            C("America/Atikokan","Atikokan","阿蒂科肯"),
            C("America/Bahia","Bahia","巴伊亚"),
            C("America/Barbados","Barbados","巴巴多斯"),
            C("America/Belem","Belem","贝伦"),
            C("America/Belize","Belize","伯利兹"),
            C("America/Boa_Vista","Boa Vista","博阿维斯塔"),
            C("America/Bogota","Bogota","波哥大"),
            C("America/Boise","Boise","博伊西"),
            C("America/Cambridge_Bay","Cambridge Bay","剑桥湾"),
            C("America/Campo_Grande","Campo Grande","大坎普"),
            C("America/Cancun","Cancun","坎昆"),
            C("America/Caracas","Caracas","加拉加斯"),
            C("America/Cayenne","Cayenne","卡宴"),
            C("America/Cayman","Cayman","开曼"),
            C("America/Chicago","Chicago","芝加哥"),
            C("America/Chihuahua","Chihuahua","奇瓦瓦"),
            C("America/Costa_Rica","Costa Rica","哥斯达黎加"),
            C("America/Creston","Creston","克雷斯顿"),
            C("America/Cuiaba","Cuiaba","库亚巴"),
            C("America/Curacao","Curacao","库拉索"),
            C("America/Danmarkshavn","Danmarkshavn","丹麦港"),
            C("America/Dawson","Dawson","道森"),
            C("America/Dawson_Creek","Dawson Creek","道森溪"),
            C("America/Denver","Denver","丹佛"),
            C("America/Detroit","Detroit","底特律"),
            C("America/Dominica","Dominica","多米尼克"),
            C("America/Edmonton","Edmonton","埃德蒙顿"),
            C("America/Eirunepe","Eirunepe","埃鲁内佩"),
            C("America/El_Salvador","El Salvador","萨尔瓦多"),
            C("America/Fort_Nelson","Fort Nelson","尼尔森堡"),
            C("America/Fortaleza","Fortaleza","福塔雷萨"),
            C("America/Glace_Bay","Glace Bay","格莱斯贝"),
            C("America/Goose_Bay","Goose Bay","古斯贝"),
            C("America/Grand_Turk","Grand Turk","大特克"),
            C("America/Grenada","Grenada","格林纳达"),
            C("America/Guadeloupe","Guadeloupe","瓜德罗普"),
            C("America/Guatemala","Guatemala","危地马拉"),
            C("America/Guayaquil","Guayaquil","瓜亚基尔"),
            C("America/Guyana","Guyana","圭亚那"),
            C("America/Halifax","Halifax","哈利法克斯"),
            C("America/Havana","Havana","哈瓦那"),
            C("America/Hermosillo","Hermosillo","埃莫西约"),
            C("America/Indiana/Indianapolis","Indianapolis","印第安纳波利斯"),
            C("America/Inuvik","Inuvik","伊努维克"),
            C("America/Iqaluit","Iqaluit","伊卡卢伊特"),
            C("America/Jamaica","Jamaica","牙买加"),
            C("America/Juneau","Juneau","朱诺"),
            C("America/Kentucky/Louisville","Louisville","路易维尔"),
            C("America/La_Paz","La Paz","拉巴斯"),
            C("America/Lima","Lima","利马"),
            C("America/Los_Angeles","Los Angeles","洛杉矶"),
            C("America/Maceio","Maceio","马塞约"),
            C("America/Managua","Managua","马那瓜"),
            C("America/Manaus","Manaus","马瑙斯"),
            C("America/Martinique","Martinique","马提尼克"),
            C("America/Matamoros","Matamoros","马塔莫罗斯"),
            C("America/Mazatlan","Mazatlan","马萨特兰"),
            C("America/Menominee","Menominee","梅诺米尼"),
            C("America/Merida","Merida","梅里达"),
            C("America/Metlakatla","Metlakatla","梅特拉卡特拉"),
            C("America/Mexico_City","Mexico City","墨西哥城"),
            C("America/Miquelon","Miquelon","密克隆"),
            C("America/Moncton","Moncton","蒙克顿"),
            C("America/Monterrey","Monterrey","蒙特雷"),
            C("America/Montevideo","Montevideo","蒙得维的亚"),
            C("America/Nassau","Nassau","拿骚"),
            C("America/New_York","New York","纽约"),
            C("America/Nome","Nome","诺姆"),
            C("America/Noronha","Noronha","诺罗尼亚"),
            C("America/Nuuk","Nuuk","努克"),
            C("America/Ojinaga","Ojinaga","奥希纳加"),
            C("America/Panama","Panama","巴拿马"),
            C("America/Paramaribo","Paramaribo","帕拉马里博"),
            C("America/Phoenix","Phoenix","凤凰城"),
            C("America/Port-au-Prince","Port-au-Prince","太子港"),
            C("America/Port_of_Spain","Port of Spain","西班牙港"),
            C("America/Porto_Velho","Porto Velho","波多韦柳"),
            C("America/Puerto_Rico","Puerto Rico","波多黎各"),
            C("America/Punta_Arenas","Punta Arenas","蓬塔阿雷纳斯"),
            C("America/Rankin_Inlet","Rankin Inlet","兰金湾"),
            C("America/Recife","Recife","累西腓"),
            C("America/Regina","Regina","里贾纳"),
            C("America/Resolute","Resolute","雷索卢特"),
            C("America/Rio_Branco","Rio Branco","里约布朗库"),
            C("America/Santarem","Santarem","圣塔伦"),
            C("America/Santiago","Santiago","圣地亚哥"),
            C("America/Santo_Domingo","Santo Domingo","圣多明各"),
            C("America/Sao_Paulo","Sao Paulo","圣保罗"),
            C("America/Scoresbysund","Scoresbysund","斯科斯比松"),
            C("America/Sitka","Sitka","锡特卡"),
            C("America/St_Johns","St Johns","圣约翰"),
            C("America/Swift_Current","Swift Current","斯威夫特卡伦特"),
            C("America/Tegucigalpa","Tegucigalpa","特古西加尔巴"),
            C("America/Thule","Thule","图勒"),
            C("America/Tijuana","Tijuana","蒂华纳"),
            C("America/Toronto","Toronto","多伦多"),
            C("America/Vancouver","Vancouver","温哥华"),
            C("America/Whitehorse","Whitehorse","白马"),
            C("America/Winnipeg","Winnipeg","温尼伯"),
            C("America/Yakutat","Yakutat","亚库塔特"),
        ]],
        [TZRegion regionWithEN:@"Antarctica" cn:@"南极洲" cities:@[
            C("Antarctica/Casey","Casey","凯西站"),
            C("Antarctica/Davis","Davis","戴维斯站"),
            C("Antarctica/DumontDUrville","Dumont d'Urville","迪蒙迪维尔"),
            C("Antarctica/Macquarie","Macquarie","麦夸里"),
            C("Antarctica/Mawson","Mawson","莫森站"),
            C("Antarctica/McMurdo","McMurdo","麦克默多"),
            C("Antarctica/Palmer","Palmer","帕默站"),
            C("Antarctica/Rothera","Rothera","罗瑟拉"),
            C("Antarctica/Syowa","Syowa","昭和站"),
            C("Antarctica/Troll","Troll","特罗尔站"),
            C("Antarctica/Vostok","Vostok","沃斯托克"),
        ]],
        [TZRegion regionWithEN:@"Asia" cn:@"亚洲" cities:@[
            C("Asia/Aden","Aden","亚丁"),
            C("Asia/Almaty","Almaty","阿拉木图"),
            C("Asia/Amman","Amman","安曼"),
            C("Asia/Anadyr","Anadyr","阿纳德尔"),
            C("Asia/Aqtau","Aqtau","阿克套"),
            C("Asia/Aqtobe","Aqtobe","阿克托别"),
            C("Asia/Ashgabat","Ashgabat","阿什哈巴德"),
            C("Asia/Atyrau","Atyrau","阿特劳"),
            C("Asia/Baghdad","Baghdad","巴格达"),
            C("Asia/Bahrain","Bahrain","巴林"),
            C("Asia/Baku","Baku","巴库"),
            C("Asia/Bangkok","Bangkok","曼谷"),
            C("Asia/Barnaul","Barnaul","巴尔瑙尔"),
            C("Asia/Beirut","Beirut","贝鲁特"),
            C("Asia/Bishkek","Bishkek","比什凯克"),
            C("Asia/Brunei","Brunei","文莱"),
            C("Asia/Chita","Chita","赤塔"),
            C("Asia/Choibalsan","Choibalsan","乔巴山"),
            C("Asia/Colombo","Colombo","科伦坡"),
            C("Asia/Damascus","Damascus","大马士革"),
            C("Asia/Dhaka","Dhaka","达卡"),
            C("Asia/Dili","Dili","帝力"),
            C("Asia/Dubai","Dubai","迪拜"),
            C("Asia/Dushanbe","Dushanbe","杜尚别"),
            C("Asia/Famagusta","Famagusta","法马古斯塔"),
            C("Asia/Gaza","Gaza","加沙"),
            C("Asia/Hebron","Hebron","希伯伦"),
            C("Asia/Ho_Chi_Minh","Ho Chi Minh","胡志明市"),
            C("Asia/Hong_Kong","Hong Kong","香港"),
            C("Asia/Hovd","Hovd","科布多"),
            C("Asia/Irkutsk","Irkutsk","伊尔库茨克"),
            C("Asia/Jakarta","Jakarta","雅加达"),
            C("Asia/Jayapura","Jayapura","查亚普拉"),
            C("Asia/Jerusalem","Jerusalem","耶路撒冷"),
            C("Asia/Kabul","Kabul","喀布尔"),
            C("Asia/Kamchatka","Kamchatka","堪察加"),
            C("Asia/Karachi","Karachi","卡拉奇"),
            C("Asia/Kathmandu","Kathmandu","加德满都"),
            C("Asia/Khandyga","Khandyga","汉德加"),
            C("Asia/Kolkata","Kolkata","加尔各答"),
            C("Asia/Krasnoyarsk","Krasnoyarsk","克拉斯诺亚尔斯克"),
            C("Asia/Kuala_Lumpur","Kuala Lumpur","吉隆坡"),
            C("Asia/Kuching","Kuching","古晋"),
            C("Asia/Kuwait","Kuwait","科威特"),
            C("Asia/Macau","Macau","澳门"),
            C("Asia/Magadan","Magadan","马加丹"),
            C("Asia/Makassar","Makassar","望加锡"),
            C("Asia/Manila","Manila","马尼拉"),
            C("Asia/Muscat","Muscat","马斯喀特"),
            C("Asia/Nicosia","Nicosia","尼科西亚"),
            C("Asia/Novokuznetsk","Novokuznetsk","新库兹涅茨克"),
            C("Asia/Novosibirsk","Novosibirsk","新西伯利亚"),
            C("Asia/Omsk","Omsk","鄂木斯克"),
            C("Asia/Oral","Oral","乌拉尔斯克"),
            C("Asia/Phnom_Penh","Phnom Penh","金边"),
            C("Asia/Pontianak","Pontianak","坤甸"),
            C("Asia/Pyongyang","Pyongyang","平壤"),
            C("Asia/Qatar","Qatar","卡塔尔"),
            C("Asia/Qostanay","Qostanay","科斯塔奈"),
            C("Asia/Qyzylorda","Qyzylorda","克孜勒奥尔达"),
            C("Asia/Riyadh","Riyadh","利雅得"),
            C("Asia/Sakhalin","Sakhalin","萨哈林"),
            C("Asia/Samarkand","Samarkand","撒马尔罕"),
            C("Asia/Seoul","Seoul","首尔"),
            C("Asia/Shanghai","Shanghai","上海"),
            C("Asia/Singapore","Singapore","新加坡"),
            C("Asia/Srednekolymsk","Srednekolymsk","中科雷姆斯克"),
            C("Asia/Taipei","Taipei","台北"),
            C("Asia/Tashkent","Tashkent","塔什干"),
            C("Asia/Tbilisi","Tbilisi","第比利斯"),
            C("Asia/Tehran","Tehran","德黑兰"),
            C("Asia/Thimphu","Thimphu","廷布"),
            C("Asia/Tokyo","Tokyo","东京"),
            C("Asia/Tomsk","Tomsk","托木斯克"),
            C("Asia/Ulaanbaatar","Ulaanbaatar","乌兰巴托"),
            C("Asia/Urumqi","Urumqi","乌鲁木齐"),
            C("Asia/Ust-Nera","Ust-Nera","乌斯季涅拉"),
            C("Asia/Vientiane","Vientiane","万象"),
            C("Asia/Vladivostok","Vladivostok","符拉迪沃斯托克"),
            C("Asia/Yakutsk","Yakutsk","雅库茨克"),
            C("Asia/Yangon","Yangon","仰光"),
            C("Asia/Yekaterinburg","Yekaterinburg","叶卡捷琳堡"),
            C("Asia/Yerevan","Yerevan","埃里温"),
        ]],
        [TZRegion regionWithEN:@"Atlantic" cn:@"大西洋" cities:@[
            C("Atlantic/Azores","Azores","亚速尔"),
            C("Atlantic/Bermuda","Bermuda","百慕大"),
            C("Atlantic/Canary","Canary","加那利"),
            C("Atlantic/Cape_Verde","Cape Verde","佛得角"),
            C("Atlantic/Faroe","Faroe","法罗"),
            C("Atlantic/Madeira","Madeira","马德拉"),
            C("Atlantic/Reykjavik","Reykjavik","雷克雅未克"),
            C("Atlantic/South_Georgia","South Georgia","南乔治亚"),
            C("Atlantic/Stanley","Stanley","斯坦利"),
        ]],
        [TZRegion regionWithEN:@"Australia" cn:@"大洋洲" cities:@[
            C("Australia/Adelaide","Adelaide","阿德莱德"),
            C("Australia/Brisbane","Brisbane","布里斯班"),
            C("Australia/Broken_Hill","Broken Hill","布罗肯希尔"),
            C("Australia/Darwin","Darwin","达尔文"),
            C("Australia/Eucla","Eucla","尤克拉"),
            C("Australia/Hobart","Hobart","霍巴特"),
            C("Australia/Lindeman","Lindeman","林德曼"),
            C("Australia/Lord_Howe","Lord Howe","豪勋爵"),
            C("Australia/Melbourne","Melbourne","墨尔本"),
            C("Australia/Perth","Perth","珀斯"),
            C("Australia/Sydney","Sydney","悉尼"),
        ]],
        [TZRegion regionWithEN:@"Europe" cn:@"欧洲" cities:@[
            C("Europe/Amsterdam","Amsterdam","阿姆斯特丹"),
            C("Europe/Andorra","Andorra","安道尔"),
            C("Europe/Astrakhan","Astrakhan","阿斯特拉罕"),
            C("Europe/Athens","Athens","雅典"),
            C("Europe/Belgrade","Belgrade","贝尔格莱德"),
            C("Europe/Berlin","Berlin","柏林"),
            C("Europe/Brussels","Brussels","布鲁塞尔"),
            C("Europe/Bucharest","Bucharest","布加勒斯特"),
            C("Europe/Budapest","Budapest","布达佩斯"),
            C("Europe/Chisinau","Chisinau","基希讷乌"),
            C("Europe/Copenhagen","Copenhagen","哥本哈根"),
            C("Europe/Dublin","Dublin","都柏林"),
            C("Europe/Gibraltar","Gibraltar","直布罗陀"),
            C("Europe/Helsinki","Helsinki","赫尔辛基"),
            C("Europe/Istanbul","Istanbul","伊斯坦布尔"),
            C("Europe/Kaliningrad","Kaliningrad","加里宁格勒"),
            C("Europe/Kirov","Kirov","基洛夫"),
            C("Europe/Kyiv","Kyiv","基辅"),
            C("Europe/Lisbon","Lisbon","里斯本"),
            C("Europe/London","London","伦敦"),
            C("Europe/Luxembourg","Luxembourg","卢森堡"),
            C("Europe/Madrid","Madrid","马德里"),
            C("Europe/Malta","Malta","马耳他"),
            C("Europe/Minsk","Minsk","明斯克"),
            C("Europe/Monaco","Monaco","摩纳哥"),
            C("Europe/Moscow","Moscow","莫斯科"),
            C("Europe/Oslo","Oslo","奥斯陆"),
            C("Europe/Paris","Paris","巴黎"),
            C("Europe/Prague","Prague","布拉格"),
            C("Europe/Riga","Riga","里加"),
            C("Europe/Rome","Rome","罗马"),
            C("Europe/Samara","Samara","萨马拉"),
            C("Europe/Saratov","Saratov","萨拉托夫"),
            C("Europe/Simferopol","Simferopol","辛菲罗波尔"),
            C("Europe/Sofia","Sofia","索非亚"),
            C("Europe/Stockholm","Stockholm","斯德哥尔摩"),
            C("Europe/Tallinn","Tallinn","塔林"),
            C("Europe/Tirane","Tirane","地拉那"),
            C("Europe/Ulyanovsk","Ulyanovsk","乌里扬诺夫斯克"),
            C("Europe/Vienna","Vienna","维也纳"),
            C("Europe/Vilnius","Vilnius","维尔纽斯"),
            C("Europe/Volgograd","Volgograd","伏尔加格勒"),
            C("Europe/Warsaw","Warsaw","华沙"),
            C("Europe/Zurich","Zurich","苏黎世"),
        ]],
        [TZRegion regionWithEN:@"Indian" cn:@"印度洋" cities:@[
            C("Indian/Antananarivo","Antananarivo","塔那那利佛"),
            C("Indian/Chagos","Chagos","查戈斯"),
            C("Indian/Christmas","Christmas","圣诞岛"),
            C("Indian/Cocos","Cocos","科科斯"),
            C("Indian/Comoro","Comoro","科摩罗"),
            C("Indian/Kerguelen","Kerguelen","凯尔盖朗"),
            C("Indian/Mahe","Mahe","马埃"),
            C("Indian/Maldives","Maldives","马尔代夫"),
            C("Indian/Mauritius","Mauritius","毛里求斯"),
            C("Indian/Mayotte","Mayotte","马约特"),
            C("Indian/Reunion","Reunion","留尼汪"),
        ]],
        [TZRegion regionWithEN:@"Pacific" cn:@"太平洋" cities:@[
            C("Pacific/Apia","Apia","阿皮亚"),
            C("Pacific/Auckland","Auckland","奥克兰"),
            C("Pacific/Bougainville","Bougainville","布干维尔"),
            C("Pacific/Chatham","Chatham","查塔姆"),
            C("Pacific/Chuuk","Chuuk","丘克"),
            C("Pacific/Easter","Easter","复活节岛"),
            C("Pacific/Efate","Efate","埃法特"),
            C("Pacific/Fakaofo","Fakaofo","法考福"),
            C("Pacific/Fiji","Fiji","斐济"),
            C("Pacific/Funafuti","Funafuti","富纳富提"),
            C("Pacific/Galapagos","Galapagos","加拉帕戈斯"),
            C("Pacific/Gambier","Gambier","甘比尔"),
            C("Pacific/Guadalcanal","Guadalcanal","瓜达尔卡纳尔"),
            C("Pacific/Guam","Guam","关岛"),
            C("Pacific/Honolulu","Honolulu","檀香山"),
            C("Pacific/Kanton","Kanton","坎顿岛"),
            C("Pacific/Kiritimati","Kiritimati","基里蒂马蒂"),
            C("Pacific/Kosrae","Kosrae","科斯雷"),
            C("Pacific/Kwajalein","Kwajalein","夸贾林"),
            C("Pacific/Majuro","Majuro","马朱罗"),
            C("Pacific/Marquesas","Marquesas","马克萨斯"),
            C("Pacific/Midway","Midway","中途岛"),
            C("Pacific/Nauru","Nauru","瑙鲁"),
            C("Pacific/Niue","Niue","纽埃"),
            C("Pacific/Norfolk","Norfolk","诺福克"),
            C("Pacific/Noumea","Noumea","努美阿"),
            C("Pacific/Pago_Pago","Pago Pago","帕果帕果"),
            C("Pacific/Palau","Palau","帕劳"),
            C("Pacific/Pitcairn","Pitcairn","皮特凯恩"),
            C("Pacific/Pohnpei","Pohnpei","波纳佩"),
            C("Pacific/Port_Moresby","Port Moresby","莫尔兹比港"),
            C("Pacific/Rarotonga","Rarotonga","拉罗汤加"),
            C("Pacific/Saipan","Saipan","塞班"),
            C("Pacific/Tahiti","Tahiti","塔希提"),
            C("Pacific/Tarawa","Tarawa","塔拉瓦"),
            C("Pacific/Tongatapu","Tongatapu","汤加塔布"),
            C("Pacific/Wake","Wake","威克岛"),
            C("Pacific/Wallis","Wallis","瓦利斯"),
        ]],
        [TZRegion regionWithEN:@"Etc (UTC offsets)" cn:@"UTC 偏移" cities:@[
            C("Etc/UTC","UTC","UTC"),
            C("Etc/GMT","GMT","GMT"),
            C("Etc/GMT+12","GMT-12","GMT-12"), C("Etc/GMT+11","GMT-11","GMT-11"),
            C("Etc/GMT+10","GMT-10","GMT-10"), C("Etc/GMT+9","GMT-9","GMT-9"),
            C("Etc/GMT+8","GMT-8","GMT-8"), C("Etc/GMT+7","GMT-7","GMT-7"),
            C("Etc/GMT+6","GMT-6","GMT-6"), C("Etc/GMT+5","GMT-5","GMT-5"),
            C("Etc/GMT+4","GMT-4","GMT-4"), C("Etc/GMT+3","GMT-3","GMT-3"),
            C("Etc/GMT+2","GMT-2","GMT-2"), C("Etc/GMT+1","GMT-1","GMT-1"),
            C("Etc/GMT-1","GMT+1","GMT+1"), C("Etc/GMT-2","GMT+2","GMT+2"),
            C("Etc/GMT-3","GMT+3","GMT+3"), C("Etc/GMT-4","GMT+4","GMT+4"),
            C("Etc/GMT-5","GMT+5","GMT+5"), C("Etc/GMT-6","GMT+6","GMT+6"),
            C("Etc/GMT-7","GMT+7","GMT+7"), C("Etc/GMT-8","GMT+8","GMT+8"),
            C("Etc/GMT-9","GMT+9","GMT+9"), C("Etc/GMT-10","GMT+10","GMT+10"),
            C("Etc/GMT-11","GMT+11","GMT+11"), C("Etc/GMT-12","GMT+12","GMT+12"),
            C("Etc/GMT-13","GMT+13","GMT+13"), C("Etc/GMT-14","GMT+14","GMT+14"),
        ]],
    ];

    NSMutableDictionary *idx = [NSMutableDictionary dictionaryWithCapacity:300];
    for (TZRegion *r in sRegions) {
        for (TZCity *c in r.cities) {
            idx[c.tz] = c;
        }
    }
    sIndex = [idx copy];
}

+ (NSArray<TZRegion *> *)regions {
    return sRegions;
}

+ (TZCity *)findCityByTZ:(NSString *)tz {
    return sIndex[tz];
}

@end

#undef C
